spring:
  application:
    name: api-gateway
  rabbitmq:
    host: 192.168.188.150
    port: 5672
    username: admin
    password: 123456
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    
zuul:
  #全部服务忽略敏感头(全部服务都可以传递cookie)
  sensitive-headers: 
  routes:
  # /myProduct/product/list -> /product/product/list
    aaaaaa:
      path: /myProduct/**
      serviceId: product
      #不过滤cookie
      sensitiveHeaders:
  #简洁写法
#    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder 
management:
  security:
    enabled: false    
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
    
server:
  port: 8086
  #解决 com.netflix.zuul.exception.ZuulException:  at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.findZuulException
  connection-timeout: 30000

env: api-gateway1
