spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.188.150:3306/zdemo_SpringCloud_Sell?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: Root_123456!
  rabbitmq:
    host: 192.168.188.150
    port: 5672
    username: admin
    password: 123456
  redis:
    host: 192.168.188.150
    port: 6379
  jpa:
    show-sql: true

  zipkin:
    base-url: http://192.168.188.150:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.openfeign: debug


server:
  port: 8083

env: order-dev
