spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    passowrd: 123456
    url: jdbc:mysql:127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&userSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
env: dev
